# Creating Employee Records
## Criação de Cadastro de Funcionários
***
### Importing Used Libraries
#### Importando as bibliotécas usadas

In [82]:
import tkinter as tk
import sqlite3
import pandas as pd

#### Description of the step by step that will be carried out
##### Descrição do passo a passo que será realizado

   - 1) Create The Database
       - 1) Criar o banco de dados
   - 2) Create The Tebal
       - 2) Criar Tabela
   - 3) Create GUI
       - 3) Criar interface gráfica
           - labels
               - rótulos
           - Entry / Input
               - Entrada
           - buttons
               - botões
        
   - 4) Integrate the bank with the buttons
       - 4) Integrar o banco com os botões
           - Creat / Register (INSERT INTO)
               - Criar / Cadastrar (INSERT INTO)
           - List (SELECT *)
               - Pandas
           - Update (UPDATE)
               - Pandas
           - Delete (DELETE)
               - Pandas
           - Detail (SELECT)
               - Pandas
           - exportar (SELECT)
               - Pandas
           - Salary Report (SELECT)
               - Pandas
           - Age Report (SELECT)
               - Pandas

***
### Criando banco de dados

In [2]:
conect = sqlite3.connect('register.db')
menseng = conect.cursor()
menseng.execute('''CREATE TABLE employ (
    ide INTEGER NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    department TEXT NOT NULL,
    salary FLOAT NOT NULL,
    birth_date TEXT NOT NULL
    )
''')

conect.commit()

conect.close()

***
#### Criando Funções

In [78]:
def employ_list():
    conect = sqlite3.connect('register.db')
    menseng = conect.cursor()
    menseng.execute("SELECT * FROM employ")
    List_record = menseng.fetchall()
    List_record = pd.DataFrame(List_record, columns= ['ID', 'Name', 'E-amil', 'Department', 'Salary', 'Birth Date'])
    display(List_record[['ID', 'Name', 'Department']])
    conect.commit()
    
    conect.close()

def employ_creat():
    conect = sqlite3.connect('register.db')
    menseng = conect.cursor()
    menseng.execute("INSERT INTO employ VALUES (:ide, :name, :email, :department, :salary, :birth_date)",
                    {
                        'ide':entry_ide.get(),
                        'name':entry_name.get(),
                        'email':entry_email.get(),
                        'department':entry_department.get(),
                        'salary':entry_salary.get(),
                        'birth_date':entry_birth_date.get()
                    }
                   )
    
    conect.commit()
    
    conect.close()
    
    entry_ide.delete(0, "end")
    entry_name.delete(0, "end")
    entry_email.delete(0, "end")
    entry_department.delete(0, "end")
    entry_salary.delete(0, "end")
    entry_birth_date.delete(0, "end")

def employ_update(): #code failure
    conect = sqlite3.connect('register.db')
    menseng = conect.cursor()
    menseng.execute("UPDATE employ VALUES (:ide, :name, :email, :department, :salary, :birth_date)",
                    {
                        'ide':entry_ide.get(),
                        'name':entry_name.get(),
                        'email':entry_email.get(),
                        'department':entry_department.get(),
                        'salary':entry_salary.get(),
                        'birth_date':entry_birth_date.get()
                    }
                   )
    
    conect.commit()
    
    conect.close()
    
    entry_ide.delete(0, "end")
    entry_name.delete(0, "end")
    entry_email.delete(0, "end")
    entry_department.delete(0, "end")
    entry_salary.delete(0, "end")
    entry_birth_date.delete(0, "end")

def employ_delete(): #code failure
    conect = sqlite3.connect('register.db')
    menseng = conect.cursor()
    menseng.execute("DELETE FROM employ WHERE ide = 'ide'",
                    {
                        'ide':entry_ide.update()
                    }
                   )
    
    conect.commit()
    
    conect.close()
    
    entry_ide.delete(0, "end")

def employ_detail():
    conect = sqlite3.connect('register.db')
    menseng = conect.cursor()
    menseng.execute("SELECT * FROM employ")
    List_record = menseng.fetchall()
    List_record = pd.DataFrame(List_record, columns= ['ID', 'Name', 'E-amil', 'Department', 'Salary', 'Birth Date'])
    display(List_record)
    conect.commit()

def salary_report():
    conect = sqlite3.connect('register.db')
    menseng = conect.cursor()
    menseng.execute("SELECT * FROM employ")
    List_record = menseng.fetchall()
    List_record = pd.DataFrame(List_record, columns= ['ID', 'Name', 'E-amil', 'Department', 'Salary', 'Birth Date'])
    display(List_record[['ID', 'Name', 'Salary']])
    conect.commit()
    
    conect.close()
    
def age_report(): #Code under review
    conect = sqlite3.connect('register.db')
    menseng = conect.cursor()
    menseng.execute("SELECT * FROM employ")
    List_record = menseng.fetchall()
    List_record = pd.DataFrame(List_record, columns= ['ID', 'Name', 'E-amil', 'Department', 'Salary', 'Birth Date'])
    age = {'01-01-1983' : 39, '01-01-1977' : 45, '01-01-1980' : 42}
    List_record['Age'] = List_record['Birth Date'].map(age)
    display(List_record[['ID', 'Name', 'Age']])
    conect.commit()
    
    conect.close()

In [81]:
# Window / Janela

window = tk.Tk()
window.title('Employee Registration Tool')

# Labels / Rótulos

label_ide = tk.Label(window, text='ID')
label_ide.grid(row=0, column=0, padx=10, pady=10)

label_name = tk.Label(window, text='Name')
label_name.grid(row=1, column=0, padx=10, pady=10)

label_email = tk.Label(window, text='E-mail')
label_email.grid(row=2, column=0, padx=10, pady=10)

label_department = tk.Label(window, text='Department')
label_department.grid(row=3, column=0, padx=10, pady=10)

label_salary = tk.Label(window, text='Salary')
label_salary.grid(row=4, column=0, padx=10, pady=10)

label_birth_date = tk.Label(window, text='Birth Date')
label_birth_date.grid(row=5, column=0, padx=10, pady=10)

# Entrys / Entradas

entry_ide = tk.Entry(window, text='ID', width= 30)
entry_ide.grid(row=0, column=1, padx=10, pady=10)

entry_name = tk.Entry(window, text='Name', width= 30)
entry_name.grid(row=1, column=1, padx=10, pady=10)

entry_email = tk.Entry(window, text='E-mail', width= 30)
entry_email.grid(row=2, column=1, padx=10, pady=10)

entry_department = tk.Entry(window, text='Department', width= 30)
entry_department.grid(row=3, column=1, padx=10, pady=10)

entry_salary = tk.Entry(window, text='Salary', width= 30)
entry_salary.grid(row=4, column=1, padx=10, pady=10)

entry_birth_date = tk.Entry(window, text='Birth Date', width= 30)
entry_birth_date.grid(row=5, column=1, padx=10, pady=10)

# Buttons / Botões

button_employ_creat = tk.Button(window, text='Register Employee', command = employ_creat)
button_employ_creat.grid(row=6, column=0, padx=10, pady=10, columnspan = 2, ipadx = 80)

button_empoly_list = tk.Button(window, text='List of Employees', command = employ_list)
button_empoly_list.grid(row=7, column=0, padx=10, pady=10)

button_employ_update = tk.Button(window, text='Employee Updates', command = employ_update)
button_employ_update.grid(row=7, column=1, padx=10, pady=10)

button_employ_delete = tk.Button(window, text='Employee Delete', command = employ_delete)
button_employ_delete.grid(row=8, column=0, padx=10, pady=10)

button_employ_detail = tk.Button(window, text='Employee Detail', command = employ_detail)
button_employ_detail.grid(row=8, column=1, padx=10, pady=10)

button_employ_salary = tk.Button(window, text='Salary Report', command = salary_report)
button_employ_salary.grid(row=9, column=0, padx=10, pady=10)

button_employ_age = tk.Button(window, text='Age Report', command = age_report)
button_employ_age.grid(row=9, column=1, padx=10, pady=10)

window.mainloop()